stages:
    - build
    
build recoveryimage:
    stage: build
    image: elxreno/twrp-build:latest
    artifacts:
        paths:
            - recovery.img
    script:
    - cd /root
    - git clone https://gitlab.com/ElXreno/android-5.1-src omni
    - cd omni
    - mkdir -p device/meizu/m3s && mv /builds/ElXreno/twrp_device_meizu_m3s/* device/meizu/m3s/
    - source build/envsetup.sh && lunch omni_m3s-eng && make -j5 recoveryimage
    - cp /root/out/target/product/m3s/recovery.img $CI_PROJECT_DIR/recovery.img