image: surendrajat/twrp-builder:latest
build:
 script:
 - mkdir $HOME/omni && cd $HOME/omni
 - repo init --depth=1 -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni.git -b twrp-6.0
 - repo sync -j 16
 - rm -rf bootable/recovery
 - git clone https://github.com/omnirom/android_bootable_recovery.git -b android-5.1 bootable/recovery
 - mkdir -p device/meizu/m3s && mv /builds/ElXreno/twrp_device_meizu_m3s/* device/meizu/m3s/
 - source build/envsetup.sh && lunch omni_m3s-eng && make -j16 recoveryimage
